# Site settings
title: FREME Documentation
email: jonathan_paul.sauder@dfki.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/doc" # the subpath of your site, e.g. /blog/
apiurl: "/current"
url: "http://api-dev.freme-project.eu" # the base hostname & protocol for your site
github_username:  josauder

# Build settings
markdown: kramdown
kramdown:
  input: GFM

pages: ./_pages	
